### ISSUE TITLE
Problem with seeding

### ISSUE THREAD

**Issue by Shayle** [ferenko/physalis#3]
You added a field "commentaires" to the "personne" model, but forgot to change the seeder, so now, when trying to seed the database, it returns an error. It should be trivial to correct though :)

**Comment by Shayle** [comment]
Moreover, if you push this change to production without making the field nullable, you'll encounter some problems as existing persons won't have a commentaires field set.

**Comment by ferenko** [comment]
Was sure to have "commentaires" nullable.
Commit correct it, and add in seeds this column.

**Comment by Shayle** [comment]
Nice one!
